apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-wms.fullname" . }}-secrets
  labels:
    {{- include "weather-wms.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ include "weather-wms.s3AccessKey" . | quote }}
  S3_SECRET_KEY: {{ include "weather-wms.s3SecretKey" . | quote }}
