[package]
name = "wms-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
wms-common = { path = "../wms-common" }
quick-xml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
