# GRIB2 WMO Standard Parameter Table
# Source: WMO Manual on Codes Table 4.2
# https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/

table:
  source: WMO
  discipline: 0  # Meteorological products
  version: master

# Discipline 0: Meteorological products
meteorological:
  # Category 0: Temperature
  temperature:
    - parameter: 0
      name: TMP
      description: "Temperature"
      units: "K"
    - parameter: 1
      name: VTMP
      description: "Virtual Temperature"
      units: "K"
    - parameter: 2
      name: POT
      description: "Potential Temperature"
      units: "K"
    - parameter: 3
      name: EPOT
      description: "Pseudo-Adiabatic Potential Temperature"
      units: "K"
    - parameter: 4
      name: TMAX
      description: "Maximum Temperature"
      units: "K"
    - parameter: 5
      name: TMIN
      description: "Minimum Temperature"
      units: "K"
    - parameter: 6
      name: DPT
      description: "Dew Point Temperature"
      units: "K"
    - parameter: 7
      name: DEPR
      description: "Dew Point Depression"
      units: "K"
    - parameter: 8
      name: LAPR
      description: "Lapse Rate"
      units: "K/m"
    - parameter: 9
      name: TMPA
      description: "Temperature Anomaly"
      units: "K"
    - parameter: 10
      name: LHTFL
      description: "Latent Heat Net Flux"
      units: "W/m^2"
    - parameter: 11
      name: SHTFL
      description: "Sensible Heat Net Flux"
      units: "W/m^2"

  # Category 1: Moisture
  moisture:
    - parameter: 0
      name: SPFH
      description: "Specific Humidity"
      units: "kg/kg"
    - parameter: 1
      name: RH
      description: "Relative Humidity"
      units: "%"
    - parameter: 2
      name: MIXR
      description: "Humidity Mixing Ratio"
      units: "kg/kg"
    - parameter: 3
      name: PWAT
      description: "Precipitable Water"
      units: "kg/m^2"
    - parameter: 4
      name: VAPP
      description: "Vapor Pressure"
      units: "Pa"
    - parameter: 5
      name: SATD
      description: "Saturation Deficit"
      units: "Pa"
    - parameter: 6
      name: EVP
      description: "Evaporation"
      units: "kg/m^2"
    - parameter: 7
      name: PRATE
      description: "Precipitation Rate"
      units: "kg/m^2/s"
    - parameter: 8
      name: APCP
      description: "Total Precipitation"
      units: "kg/m^2"
    - parameter: 9
      name: NCPCP
      description: "Large Scale Precipitation"
      units: "kg/m^2"
    - parameter: 10
      name: ACPCP
      description: "Convective Precipitation"
      units: "kg/m^2"
    - parameter: 11
      name: SNOD
      description: "Snow Depth"
      units: "m"
    - parameter: 12
      name: SRWEQ
      description: "Snowfall Rate Water Equivalent"
      units: "kg/m^2/s"
    - parameter: 13
      name: WEASD
      description: "Water Equivalent of Accumulated Snow Depth"
      units: "kg/m^2"

  # Category 2: Momentum
  momentum:
    - parameter: 0
      name: WDIR
      description: "Wind Direction"
      units: "degrees"
    - parameter: 1
      name: WIND
      description: "Wind Speed"
      units: "m/s"
    - parameter: 2
      name: UGRD
      description: "U-Component of Wind"
      units: "m/s"
    - parameter: 3
      name: VGRD
      description: "V-Component of Wind"
      units: "m/s"
    - parameter: 4
      name: STRM
      description: "Stream Function"
      units: "m^2/s"
    - parameter: 5
      name: VPOT
      description: "Velocity Potential"
      units: "m^2/s"
    - parameter: 6
      name: MNTSF
      description: "Montgomery Stream Function"
      units: "m^2/s^2"
    - parameter: 7
      name: SGCVV
      description: "Sigma Coordinate Vertical Velocity"
      units: "1/s"
    - parameter: 8
      name: VVEL
      description: "Vertical Velocity (pressure)"
      units: "Pa/s"
    - parameter: 9
      name: DZDT
      description: "Vertical Velocity (geometric)"
      units: "m/s"
    - parameter: 10
      name: ABSV
      description: "Absolute Vorticity"
      units: "1/s"
    - parameter: 11
      name: ABSD
      description: "Absolute Divergence"
      units: "1/s"
    - parameter: 12
      name: RELV
      description: "Relative Vorticity"
      units: "1/s"
    - parameter: 13
      name: RELD
      description: "Relative Divergence"
      units: "1/s"
    - parameter: 14
      name: PVORT
      description: "Potential Vorticity"
      units: "K*m^2/kg/s"
    - parameter: 15
      name: VUCSH
      description: "Vertical U-Component Shear"
      units: "1/s"
    - parameter: 16
      name: VVCSH
      description: "Vertical V-Component Shear"
      units: "1/s"
    - parameter: 17
      name: UFLX
      description: "Momentum Flux, U-Component"
      units: "N/m^2"
    - parameter: 18
      name: VFLX
      description: "Momentum Flux, V-Component"
      units: "N/m^2"
    - parameter: 19
      name: WMIXE
      description: "Wind Mixing Energy"
      units: "J"
    - parameter: 20
      name: BLYDP
      description: "Boundary Layer Dissipation"
      units: "W/m^2"
    - parameter: 21
      name: MAXGUST
      description: "Maximum Wind Speed"
      units: "m/s"
    - parameter: 22
      name: GUST
      description: "Wind Speed (Gust)"
      units: "m/s"

  # Category 3: Mass
  mass:
    - parameter: 0
      name: PRES
      description: "Pressure"
      units: "Pa"
    - parameter: 1
      name: PRMSL
      description: "Pressure Reduced to MSL"
      units: "Pa"
    - parameter: 2
      name: PTEND
      description: "Pressure Tendency"
      units: "Pa/s"
    - parameter: 3
      name: ICAHT
      description: "ICAO Standard Atmosphere Reference Height"
      units: "m"
    - parameter: 4
      name: GP
      description: "Geopotential"
      units: "m^2/s^2"
    - parameter: 5
      name: HGT
      description: "Geopotential Height"
      units: "gpm"
    - parameter: 6
      name: DIST
      description: "Geometric Height"
      units: "m"
    - parameter: 7
      name: HSTDV
      description: "Standard Deviation of Height"
      units: "m"
    - parameter: 8
      name: PRESA
      description: "Pressure Anomaly"
      units: "Pa"
    - parameter: 9
      name: GPA
      description: "Geopotential Height Anomaly"
      units: "gpm"
    - parameter: 10
      name: DEN
      description: "Density"
      units: "kg/m^3"
    - parameter: 11
      name: ALTS
      description: "Altimeter Setting"
      units: "Pa"
    - parameter: 12
      name: THICK
      description: "Thickness"
      units: "m"
    - parameter: 13
      name: PRESALT
      description: "Pressure Altitude"
      units: "m"
    - parameter: 14
      name: DENALT
      description: "Density Altitude"
      units: "m"

  # Category 6: Cloud
  cloud:
    - parameter: 0
      name: CICE
      description: "Cloud Ice"
      units: "kg/m^2"
    - parameter: 1
      name: TCDC
      description: "Total Cloud Cover"
      units: "%"
    - parameter: 2
      name: CDCON
      description: "Convective Cloud Cover"
      units: "%"
    - parameter: 3
      name: LCDC
      description: "Low Cloud Cover"
      units: "%"
    - parameter: 4
      name: MCDC
      description: "Medium Cloud Cover"
      units: "%"
    - parameter: 5
      name: HCDC
      description: "High Cloud Cover"
      units: "%"
    - parameter: 6
      name: CWAT
      description: "Cloud Water"
      units: "kg/m^2"
    - parameter: 7
      name: CDCA
      description: "Cloud Amount"
      units: "%"
    - parameter: 8
      name: CDCT
      description: "Cloud Type"
      units: "code"
    - parameter: 9
      name: TMAXT
      description: "Thunderstorm Maximum Tops"
      units: "m"
    - parameter: 10
      name: THUNC
      description: "Thunderstorm Coverage"
      units: "code"
    - parameter: 11
      name: CDCB
      description: "Cloud Base"
      units: "m"
    - parameter: 12
      name: CDCT
      description: "Cloud Top"
      units: "m"
    - parameter: 13
      name: CEIL
      description: "Ceiling"
      units: "m"

  # Category 7: Thermodynamic Stability
  stability:
    - parameter: 0
      name: PLI
      description: "Parcel Lifted Index"
      units: "K"
    - parameter: 1
      name: BLI
      description: "Best Lifted Index"
      units: "K"
    - parameter: 2
      name: KX
      description: "K Index"
      units: "K"
    - parameter: 3
      name: KOX
      description: "KO Index"
      units: "K"
    - parameter: 4
      name: TOTALX
      description: "Total Totals Index"
      units: "K"
    - parameter: 5
      name: SX
      description: "Sweat Index"
      units: "numeric"
    - parameter: 6
      name: CAPE
      description: "Convective Available Potential Energy"
      units: "J/kg"
    - parameter: 7
      name: CIN
      description: "Convective Inhibition"
      units: "J/kg"
    - parameter: 8
      name: HLCY
      description: "Storm Relative Helicity"
      units: "m^2/s^2"
    - parameter: 9
      name: EHLX
      description: "Energy Helicity Index"
      units: "numeric"

  # Category 15: Radar
  radar:
    - parameter: 0
      name: BSWID
      description: "Base Spectrum Width"
      units: "m/s"
    - parameter: 1
      name: BREF
      description: "Base Reflectivity"
      units: "dB"
    - parameter: 2
      name: BRVEL
      description: "Base Radial Velocity"
      units: "m/s"
    - parameter: 3
      name: VIL
      description: "Vertically Integrated Liquid"
      units: "kg/m^2"
    - parameter: 4
      name: LMAXBR
      description: "Layer Maximum Base Reflectivity"
      units: "dB"
    - parameter: 5
      name: PREC
      description: "Precipitation"
      units: "kg/m^2"
    - parameter: 6
      name: RDSP1
      description: "Radar Spectra (1)"
      units: "-"
    - parameter: 7
      name: RDSP2
      description: "Radar Spectra (2)"
      units: "-"
    - parameter: 8
      name: RDSP3
      description: "Radar Spectra (3)"
      units: "-"

  # Category 19: Physical Atmospheric Properties
  atmospheric:
    - parameter: 0
      name: VIS
      description: "Visibility"
      units: "m"
    - parameter: 1
      name: ALBDO
      description: "Albedo"
      units: "%"
    - parameter: 2
      name: TSTM
      description: "Thunderstorm Probability"
      units: "%"
    - parameter: 3
      name: MIXHT
      description: "Mixed Layer Depth"
      units: "m"
    - parameter: 4
      name: VOLASH
      description: "Volcanic Ash"
      units: "code"
    - parameter: 5
      name: ICIT
      description: "Icing Top"
      units: "m"
    - parameter: 6
      name: ICIB
      description: "Icing Base"
      units: "m"
    - parameter: 7
      name: ICI
      description: "Icing"
      units: "code"
    - parameter: 8
      name: TURBT
      description: "Turbulence Top"
      units: "m"
    - parameter: 9
      name: TURBB
      description: "Turbulence Base"
      units: "m"
    - parameter: 10
      name: TURB
      description: "Turbulence"
      units: "code"
    - parameter: 11
      name: TKE
      description: "Turbulent Kinetic Energy"
      units: "J/kg"
