[package]
name = "grib2-parser"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
chrono = { workspace = true }
grib = { workspace = true }
bytes = "1.11.0"

[dev-dependencies]
